# Pandas Practice — Banking Dataset

Run the cells from top to bottom. Each section displays the results for its questions.

In [1]:
import pandas as pd

data = {
    "Customer_ID": [101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120],
    "Name": ["Anu","Rahul","Meera","Arun","Priya","Vivek","Sneha","Akhil","Divya","Rohan","Neha","Kiran","Anjali","Manu","Swathi","Aditya","Lakshmi","Nikhil","Pooja","Sanjay"],
    "Age": [25,34,29,45,31,52,27,38,41,24,36,48,30,55,26,43,33,39,28,50],
    "City": ["Kochi","Calicut","Kochi","Bangalore","Chennai","Kochi","Calicut","Chennai","Bangalore","Kochi","Calicut","Kochi","Chennai","Bangalore","Kochi","Calicut","Bangalore","Kochi","Chennai","Calicut"],
    "Account_Type": ["Savings","Current","Savings","Current","Savings","Savings","Current","Savings","Current","Savings","Savings","Current","Savings","Current","Savings","Savings","Current","Savings","Savings","Current"],
    "Balance": [25000,85000,45000,120000,30000,75000,150000,28000,95000,18000,65000,110000,52000,175000,22000,48000,135000,35000,41000,90000],
    "Loan_Amount": [0,500000,200000,800000,0,300000,1000000,0,600000,0,250000,700000,0,900000,0,150000,450000,0,100000,350000],
    "Credit_Score": [780,690,720,650,810,735,620,770,680,820,710,640,790,600,805,750,670,760,795,630],
    "Transactions": [15,32,21,45,18,27,51,14,39,12,29,42,24,55,16,31,47,22,19,36]
}

df = pd.DataFrame(data)
df

,Customer_ID,Name,Age,City,Account_Type,Balance,Loan_Amount,Credit_Score,Transactions
0,101,Anu,25,Kochi,Savings,25000,0,780,15
1,102,Rahul,34,Calicut,Current,85000,500000,690,32
2,103,Meera,29,Kochi,Savings,45000,200000,720,21
3,104,Arun,45,Bangalore,Current,120000,800000,650,45
4,105,Priya,31,Chennai,Savings,30000,0,810,18
5,106,Vivek,52,Kochi,Savings,75000,300000,735,27
6,107,Sneha,27,Calicut,Current,150000,1000000,620,51
7,108,Akhil,38,Chennai,Savings,28000,0,770,14
8,109,Divya,41,Bangalore,Current,95000,600000,680,39
9,110,Rohan,24,Kochi,Savings,18000,0,820,12
10,111,Neha,36,Calicut,Savings,65000,250000,710,29
11,112,Kiran,48,Kochi,Current,110000,700000,640,42
12,113,Anjali,30,Chennai,Savings,52000,0,790,24
13,114,Manu,55,Bangalore,Current,175000,900000,600,55
14,115,Swathi,26,Kochi,Savings,22000,0,805,16
15,116,Aditya,43,Calicut,Savings,48000,150000,750,31
16,117,Lakshmi,33,Bangalore,Current,135000,450000,670,47
17,118,Nikhil,39,Kochi,Savings,35000,0,760,22
18,119,Pooja,28,Chennai,Savings,41000,100000,795,19
19,120,Sanjay,50,Calicut,Current,90000,350000,630,36

## Level 1 — Basic Pandas

1. Complete dataset · 2. First five customers · 3. Last five customers · 4. DataFrame shape · 5. Names and cities

In [2]:
print("1. Complete dataset")
display(df)

print("2. First 5 customers")
display(df.head())

print("3. Last 5 customers")
display(df.tail())

print(f"4. Shape: Rows: {df.shape[0]}, Columns: {df.shape[1]}")

print("5. Customer names and cities")
display(df[["Name", "City"]])

1. Complete dataset

,Customer_ID,Name,Age,City,Account_Type,Balance,Loan_Amount,Credit_Score,Transactions
0,101,Anu,25,Kochi,Savings,25000,0,780,15
1,102,Rahul,34,Calicut,Current,85000,500000,690,32
2,103,Meera,29,Kochi,Savings,45000,200000,720,21
3,104,Arun,45,Bangalore,Current,120000,800000,650,45
4,105,Priya,31,Chennai,Savings,30000,0,810,18
5,106,Vivek,52,Kochi,Savings,75000,300000,735,27
6,107,Sneha,27,Calicut,Current,150000,1000000,620,51
7,108,Akhil,38,Chennai,Savings,28000,0,770,14
8,109,Divya,41,Bangalore,Current,95000,600000,680,39
9,110,Rohan,24,Kochi,Savings,18000,0,820,12
10,111,Neha,36,Calicut,Savings,65000,250000,710,29
11,112,Kiran,48,Kochi,Current,110000,700000,640,42
12,113,Anjali,30,Chennai,Savings,52000,0,790,24
13,114,Manu,55,Bangalore,Current,175000,900000,600,55
14,115,Swathi,26,Kochi,Savings,22000,0,805,16
15,116,Aditya,43,Calicut,Savings,48000,150000,750,31
16,117,Lakshmi,33,Bangalore,Current,135000,450000,670,47
17,118,Nikhil,39,Kochi,Savings,35000,0,760,22
18,119,Pooja,28,Chennai,Savings,41000,100000,795,19
19,120,Sanjay,50,Calicut,Current,90000,350000,630,36

2. First 5 customers

,Customer_ID,Name,Age,City,Account_Type,Balance,Loan_Amount,Credit_Score,Transactions
0,101,Anu,25,Kochi,Savings,25000,0,780,15
1,102,Rahul,34,Calicut,Current,85000,500000,690,32
2,103,Meera,29,Kochi,Savings,45000,200000,720,21
3,104,Arun,45,Bangalore,Current,120000,800000,650,45
4,105,Priya,31,Chennai,Savings,30000,0,810,18

3. Last 5 customers

,Customer_ID,Name,Age,City,Account_Type,Balance,Loan_Amount,Credit_Score,Transactions
15,116,Aditya,43,Calicut,Savings,48000,150000,750,31
16,117,Lakshmi,33,Bangalore,Current,135000,450000,670,47
17,118,Nikhil,39,Kochi,Savings,35000,0,760,22
18,119,Pooja,28,Chennai,Savings,41000,100000,795,19
19,120,Sanjay,50,Calicut,Current,90000,350000,630,36

4. Shape: Rows: 20, Columns: 9
5. Customer names and cities

       Name       City
0       Anu      Kochi
1     Rahul    Calicut
2     Meera      Kochi
3      Arun  Bangalore
4     Priya    Chennai
5     Vivek      Kochi
6     Sneha    Calicut
7     Akhil    Chennai
8     Divya  Bangalore
9     Rohan      Kochi
10     Neha    Calicut
11    Kiran      Kochi
12   Anjali    Chennai
13     Manu  Bangalore
14   Swathi      Kochi
15   Aditya    Calicut
16  Lakshmi  Bangalore
17   Nikhil      Kochi
18    Pooja    Chennai
19   Sanjay    Calicut

## Level 2 — Filtering

6. Balance over ₹50,000 · 7. Age under 30 · 8. Kochi customers · 9. Credit score over 750 · 10. Customers with a loan

In [3]:
print("6. Balance greater than ₹50,000")
display(df.loc[df["Balance"] > 50000, ["Name", "Balance"]])

print("7. Customers younger than 30")
display(df.loc[df["Age"] < 30, ["Name", "Age", "City"]])

print("8. Customers from Kochi")
display(df.loc[df["City"] == "Kochi"])

print("9. Credit score greater than 750")
display(df.loc[df["Credit_Score"] > 750, ["Name", "Credit_Score"]])

print("10. Customers who have taken a loan")
display(df.loc[df["Loan_Amount"] > 0, ["Name", "Loan_Amount"]])

6. Balance greater than ₹50,000

       Name  Balance
1     Rahul    85000
3      Arun   120000
5     Vivek    75000
6     Sneha   150000
8     Divya    95000
10     Neha    65000
11    Kiran   110000
12   Anjali    52000
13     Manu   175000
16  Lakshmi   135000
19   Sanjay    90000

7. Customers younger than 30

      Name  Age     City
0      Anu   25    Kochi
2    Meera   29    Kochi
6    Sneha   27  Calicut
9    Rohan   24    Kochi
14  Swathi   26    Kochi
18   Pooja   28  Chennai

8. Customers from Kochi

,Customer_ID,Name,Age,City,Account_Type,Balance,Loan_Amount,Credit_Score,Transactions
0,101,Anu,25,Kochi,Savings,25000,0,780,15
2,103,Meera,29,Kochi,Savings,45000,200000,720,21
5,106,Vivek,52,Kochi,Savings,75000,300000,735,27
9,110,Rohan,24,Kochi,Savings,18000,0,820,12
11,112,Kiran,48,Kochi,Current,110000,700000,640,42
14,115,Swathi,26,Kochi,Savings,22000,0,805,16
17,118,Nikhil,39,Kochi,Savings,35000,0,760,22

9. Credit score greater than 750

      Name  Credit_Score
0      Anu           780
4    Priya           810
7    Akhil           770
9    Rohan           820
12  Anjali           790
14  Swathi           805
17  Nikhil           760
18   Pooja           795

10. Customers who have taken a loan

       Name  Loan_Amount
1     Rahul       500000
2     Meera       200000
3      Arun       800000
5     Vivek       300000
6     Sneha      1000000
8     Divya       600000
10     Neha       250000
11    Kiran       700000
13     Manu       900000
15   Aditya       150000
16  Lakshmi       450000
18    Pooja       100000
19   Sanjay       350000

## Level 3 — Calculations

11. Total bank balance · 12. Average balance · 13. Highest balance · 14. Lowest credit score · 15. Total loans given

In [4]:
print(f"11. Total bank balance: ₹{df['Balance'].sum():,}")
print(f"12. Average account balance: ₹{df['Balance'].mean():,.2f}")

print("13. Customer with the highest balance")
display(df.loc[[df["Balance"].idxmax()], ["Name", "Balance"]])

print("14. Customer with the lowest credit score")
display(df.loc[[df["Credit_Score"].idxmin()], ["Name", "Credit_Score"]])

print(f"15. Total loan amount given by the bank: ₹{df['Loan_Amount'].sum():,}")

11. Total bank balance: ₹1,444,000
12. Average account balance: ₹72,200.00
13. Customer with the highest balance

    Name  Balance
13  Manu   175000

14. Customer with the lowest credit score

    Name  Credit_Score
13  Manu           600

15. Total loan amount given by the bank: ₹6,300,000

## Level 4 — Grouping

16. Average balance by city · 17. Customer count by account type · 18. Average credit score by account type

In [5]:
print("16. Average balance by city")
display(df.groupby("City")["Balance"].mean().rename("Average Balance").to_frame())

print("17. Number of customers in each account type")
display(df["Account_Type"].value_counts().rename("Customer Count").to_frame())

print("18. Average credit score by account type")
display(df.groupby("Account_Type")["Credit_Score"].mean().rename("Average Credit Score").to_frame())

16. Average balance by city

           Average Balance
City
Bangalore    131250.000000
Calicut       87600.000000
Chennai       37750.000000
Kochi         47142.857143

17. Number of customers in each account type

              Customer Count
Account_Type
Savings                   12
Current                    8

18. Average credit score by account type

              Average Credit Score
Account_Type
Current                 647.500000
Savings                 770.416667

## Level 5 — Real Banking Analysis

19. Categorize customers based on balance. 20. Mark customers eligible when their credit score is at least 700 **and** their balance is at least ₹30,000.

In [6]:
df["Customer_Category"] = [
    "Premium" if balance >= 100000 else "Regular" if balance >= 50000 else "Basic"
    for balance in df["Balance"]
]
print("19. Customer categories")
display(df[["Name", "Balance", "Customer_Category"]])

df["Loan_Eligible"] = (
    (df["Credit_Score"] >= 700) & (df["Balance"] >= 30000)
).map({True: "Eligible", False: "Not Eligible"})
print("20. Loan eligibility")
display(df[["Name", "Credit_Score", "Balance", "Loan_Eligible"]])

19. Customer categories

       Name  Balance Customer_Category
0       Anu    25000             Basic
1     Rahul    85000           Regular
2     Meera    45000             Basic
3      Arun   120000           Premium
4     Priya    30000             Basic
5     Vivek    75000           Regular
6     Sneha   150000           Premium
7     Akhil    28000             Basic
8     Divya    95000           Regular
9     Rohan    18000             Basic
10     Neha    65000           Regular
11    Kiran   110000           Premium
12   Anjali    52000           Regular
13     Manu   175000           Premium
14   Swathi    22000             Basic
15   Aditya    48000             Basic
16  Lakshmi   135000           Premium
17   Nikhil    35000             Basic
18    Pooja    41000             Basic
19   Sanjay    90000           Regular

20. Loan eligibility

       Name  Credit_Score  Balance Loan_Eligible
0       Anu           780    25000  Not Eligible
1     Rahul           690    85000  Not Eligible
2     Meera           720    45000      Eligible
3      Arun           650   120000  Not Eligible
4     Priya           810    30000      Eligible
5     Vivek           735    75000      Eligible
6     Sneha           620   150000  Not Eligible
7     Akhil           770    28000  Not Eligible
8     Divya           680    95000  Not Eligible
9     Rohan           820    18000  Not Eligible
10     Neha           710    65000      Eligible
11    Kiran           640   110000  Not Eligible
12   Anjali           790    52000      Eligible
13     Manu           600   175000  Not Eligible
14   Swathi           805    22000  Not Eligible
15   Aditya           750    48000      Eligible
16  Lakshmi           670   135000  Not Eligible
17   Nikhil           760    35000      Eligible
18    Pooja           795    41000      Eligible
19   Sanjay           630    90000  Not Eligible

## Bonus Challenge

Find the city with the highest average customer balance, then count customers in that city whose credit score is above 700.

In [7]:
average_balance_by_city = df.groupby("City")["Balance"].mean()
top_city = average_balance_by_city.idxmax()
customers_above_700 = df.loc[
    (df["City"] == top_city) & (df["Credit_Score"] > 700)
]

print("Average customer balance by city:")
display(average_balance_by_city.rename("Average Balance").to_frame())
print(f"City with the highest average balance: {top_city}")
print(f"Customers in {top_city} with credit score above 700: {len(customers_above_700)}")
display(customers_above_700[["Name", "Credit_Score", "Balance"]])

Average customer balance by city:

           Average Balance
City
Bangalore    131250.000000
Calicut       87600.000000
Chennai       37750.000000
Kochi         47142.857143

City with the highest average balance: Bangalore
Customers in Bangalore with credit score above 700: 0

Empty DataFrame
Columns: [Name, Credit_Score, Balance]
Index: []